### ISSUE TITLE
wrong URL for Skype for Business admin center

### ISSUE THREAD

**Issue by limjianan-camelody** [adamfowlerit/adamfowlerit.github.io#10]
Skype for Business admin center have been migrated to teams
https://admin.teams.microsoft.com/

https://docs.microsoft.com/en-us/MicrosoftTeams/skype-for-business-settings?toc=/skypeforbusiness/sfbotoc/toc.json&bc=/skypeforbusiness/breadcrumb/toc.json

Skype for Business settings were previously in Legacy portal in the Microsoft Teams admin center. With the retirement of the legacy portal, we migrated the settings to these new locations in the Teams admin center for Skype for Business management.

**Comment by adamfowlerit** [comment]
Is the old portal functional in any way? It still seems to exist - I've added (depricated) next to the name, but if it's completely 100% decommissioned, I'll remove it

**Comment by limjianan-camelody** [comment]
i picked up the website was changed from https://admin.powerplatform.microsoft.com/ to https://webdir2a.online.lync.com/LSCP
in that case that better .. because I really can't find the old link anymore..
