### ISSUE TITLE
Self Service Password Reset, Forgot Password and Self Service Password Reset Setup

### ISSUE THREAD

**Issue by limjianan-camelody** [adamfowlerit/adamfowlerit.github.io#11]
both Self Service Password Reset and  Forgot Password point to the same location, in this case, I suggest to add https://aka.ms/SSPRSetup to set up the self-service password reset

**Comment by adamfowlerit** [comment]
Good pickup, corrected and narrowed down to one. I am thinking of having another column purely for aka.ms links so both those and the actual source are captured - testing now.
