### ISSUE TITLE
Suggestion for new URL 

### ISSUE THREAD

**Issue by limjianan-camelody** [adamfowlerit/adamfowlerit.github.io#12]
https://aka.ms/pim/tokenrefresh  = privilege identity management page
http://connectivity.microsoft.com/    = Connectivity check prior to onboard to Office 365
https://testconnectivity.microsoft.com  = famous test connectivity page for IT admin
https://mha.azurewebsites.net/ = famous page to check message header
https://o365atp.com/ = convert safe link to original URL
https://myapps.microsoft.com/ = My Apps 3 - this always redirect to which ever myapps it will be. 
https://account.activedirectory.windowsazure.com/ChangePassword.aspx   - Change password 
http://whatismytenantid.com/  - what is my tenant id - powered by sharedgate

**Comment by adamfowlerit** [comment]
Great suggestions, all added as well as a 3rd party section at the bottom.
